### ISSUE TITLE
Comments user is always "A discourse user"

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/multi-dreams#421]
User names are not shown on comments, instead all comments seem to be written by "A discourse user".

**Comment by gustavlrsn** [comment]
Fixed

**Comment by francesca-sp** [comment]
I just checked this now and am still experiencing this bug, as well as needing  to reload for the comment to be visible.

**Comment by aerugo** [comment]
Same here @gustavlrsn

**Comment by gustavlrsn** [comment]
It hadn't been deployed because of an unrelated missing script, fixed now
